base_url = "https://heka.no"
title = "heka.no"
description = "henrik's personal website"
author = "Henrik Næss"

compile_sass = true
minify_html = true

default_language = "en"
generate_feed = true

external_links_target_blank = true
external_links_no_referrer = true

[markdown]
highlight_code = true
highlight_theme = "ayu-dark"
render_emoji = true

[extra]
